<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
	/**
	 * Retourne les articles postés durant l'année courante
	 */
	public function getArticleByYear(){
		$currentDate = new \DateTime();
		$currentYear = $currentDate->format("Y"); // Année courante
		
		$queryBuilder = $this->createQueryBuilder("b");
		
		$queryBuilder->where("b.date >= :newyearday")
			->setParameter("newyearday", $currentYear . "01-01")
			->andWhere("b.date <= :slyday")
			->setParameter("slyday", $currentYear . "12-31");
		
		return $queryBuilder->getQuery()->getResult(); 
		
	}
}
