<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
	/**
	 * C'est juste la réécriture de getDoctrine()->getManager()->getRepository("BlogBundle:Commentaire")->findAll()
	 * @return ArrayCollection
	 */
	public function allComments(){
		$queryBuilder = $this->createQueryBuilder("c");
		
		/**
		 * Magique : getQuery()
		 * SELECT c.id, c.contenu, c.auteur, c.date FROM commentaire
		 * @var unknown $query
		 */
		$query = $queryBuilder->getQuery();
		
		return $query->getResult(); // Retourne toutes les lignes de la table Commentaire
	}
}
